### ISSUE TITLE
Adicionar arquivo README

### ISSUE THREAD

**Issue by MrErlison** [wvbwagner/Python-Bootcamp#1]
Precisa adicionar um arquivo README com os seguintes itens

- Link do curso
- Descrição
- Módulos e se possível atividades que serão desenrolvidas

**Comment by MrErlison** [comment]
@wvbwagner criei um PR #3 com o link do curso e todos os módulos dos 100 dias.

**Comment by wvbwagner** [comment]
Ficou excelente! Merge já feito!
