### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by MrErlison** [wvbwagner/Python-Bootcamp#8]
https://github.com/wvbwagner/Python-Bootcamp/blob/cf6b24633a50a81715b239849d56082e6529630f/days/day02/lifeinweeks.py#L6

O que é dleft, wleft, etc? Eu sei o significado hoje.

Leia mais
- [https://pt.wikipedia.org/wiki/CamelCase](https://pt.wikipedia.org/wiki/CamelCase)
- [https://www.tabnews.com.br/allangrds/cheatsheet-de-nomeclatura-de-variaveis-e-funcoes](https://www.tabnews.com.br/allangrds/cheatsheet-de-nomeclatura-de-variaveis-e-funcoes)
-

**Comment by wvbwagner** [comment]
Fixed!!!
